### ISSUE TITLE
请教一下 代码中@next是做什么用的？

### ISSUE THREAD

**Issue by 759803573** [MichaelRoshen/RedPaket#1]
[code](https://github.com/MichaelRoshen/RedPaket/blob/master/red_packet.rb#L18)

**Comment by MichaelRoshen** [comment]
@759803573 
x, y = self.class.gaussian
高斯分布返回得是一对值x,y, 作用就是依次返回x,y 而不是两个一起返回
@valid默认为false，程序返回x的的同时，@next = y, @valid=true, 下次获取随机数的时候直接返回@next
